Repository Automattic/_s, pull requests merged in 2020-04, with the labels that each got.

#1367 escape get_the_title
  comments.php
  inc/template-tags.php
  template-parts/content-page.php
  template-parts/content.php
Labels: Suggest Merge

#1394 Remove columns wrapper and hardcoded values from WooCommerce
  inc/woocommerce.php
  sass/shop/_products.scss
  woocommerce.css
Labels: WooCommerce

#1303 Remove unnecessary aria-expanded attribute on ul
  js/navigation.js
Labels: Suggest Merge

#1404 Remove an unnecessary ARIA role
  inc/woocommerce.php
Labels: WooCommerce

#1406 Fix the WooCommerce gallery zoom and gallery lightbox
  sass/shop/_single-product.scss
  woocommerce.css
Labels: Styling, WooCommerce

#1251 Refactor _S to modern CSS layout standards using grid and flex
  404.php
  README.md
  archive.php
  footer.php
  header.php
  inc/woocommerce.php
  index.php
  layouts/content-sidebar.css
  layouts/sidebar-content.css
  page.php
  sass/layout/_content-sidebar.scss
  sass/layout/_sidebar-content.scss
  sass/mixins/_mixins-master.scss
  sass/modules/_accessibility.scss
  sass/modules/_clearings.scss
  sass/navigation/_menus.scss
  sass/shop/_components.scss
  sass/shop/_products.scss
  sass/shop/_single-product.scss
  sass/style.scss
  search.php
  single.php
  style-rtl.css
  style.css
  woocommerce.css
Labels: Help wanted, Needs Testing

#960 `float` implies the use of the block layout
  sass/modules/_alignments.scss
  style-rtl.css
  style.css
Labels: Needs Refresh
